name: runs
title: Runs Manager
version: '1.0.0'
summary: A tool for managing runs
description: A tool for managing runs
base: core18
confinement: devmode
apps:
  runs:
    command: java -jar $SNAP/jar/runs-manager.jar
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH


parts:
  runs:
    plugin: gradle
    source: https://github.com/ethanabrooks/runs-manager.git
    source-tag: master
