name: runs-manager
title: Runs Manager
version: '1.0.0'
summary: A tool for managing runs
description: A tool for managing runs
base: core18
confinement: devmode
apps:
  runs-manager:
    command: bin/runs-manager
    environment:
      JAVA_HOME: $SNAP/usr/lib/jvm/java-11-openjdk-amd64
      PATH: $JAVA_HOME/jre/bin:$PATH


parts:
  runs-manager:
    plugin: gradle
    source: https://github.com/ethanabrooks/runs-manager.git
    source-tag: release-$SNAPCRAFT_PROJECT_VERSION
    override-build: |
      snapcraftctl build
      ./gradlew installDist
    plugin: dump
    source: .
    organize:
      build/install/runs-manager/bin/runs-manager: bin/
